### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by rodzappa** [state-adapt/state-adapt#2]
Hi Mike, first of all, I would like to thank you for this work.
Your approach is concise and smart, avoiding a lot of boilerplate on using redux patterns.

Said that, let me point out the purpose of this issue:

"The npmjs.com registry doesn't received the bugfix related to #1 and isn't updated with the main branch"

Best regards!

**Comment by mfp22** [comment]
@rodzappa Sorry about that, just published the fix. it is in version 0.36.0. 

I'm glad you like it. I haven't personally applied it to a large app yet, so I can't recommend putting it in production, but at the same time I see no reason it shouldn't be able to scale. But I would love to help if you run into any issues with whatever you are trying it out on. Just let me know.

**Comment by rodzappa** [comment]
@mfp22 I'm starting a long term project and intend to use it at once. 
In case of troubles, my fallback will be using pure ngrx state store, nevertheless I hope this won't be necessary.
I would appreciate any help whenever needed and I offer my feedback, thoughs and contribution to this project. 
As soon as possible I will open a new issue ticket and send a pull request to replace the lodash module for the lodash-es module, due to optimaztion warnings trigeered by ivy compiler.

**Comment by mfp22** [comment]
@rodzappa Awesome, any help is welcome! :)

I'm working on a shopping example which should involve 3 state adapters. You can probably see the naming convention I've started, but if you want to create a demo app it should be `ng-sa-<app-name>` if it is just using StateAdapt. I plan on doing a lot of side-by-side comparisons with other libraries, so that's why I like that prefix. 

In the docs app itself I was planning on removing demo apps and only linking to StackBlitz projects for the demos. You may have seen, but I wrote some scripts to allow quickly publishing apps onto StackBlitz. But there are 2 things I wanted to do in the docs app itself soon:
1. Publish actual documentation of each function in StateAdapt, like `join`, `init`, `initGet`, etc...
2. Develop a nice UI for displaying adapters so when I publish my adapter library it will be easy to see exactly what each of them does

But at the moment I feel like I need to write more posts and show more examples. People really like examples.
