### ISSUE TITLE
How to access state from one store from a different store's adapter?

### ISSUE THREAD

**Issue by kyle-mcknight** [state-adapt/state-adapt#23]
I'm working on a small project with your library to try it out. It's a bit different than what I'm used to. I have a source that emits an ID of an object that belongs in one store (`storeA`). I then need to respond to this event in another store/adapter (`storeB`, `adapterB`), but I need extra info about the object that is in `storeA` in the reducer for that source within `storeB`. 

What's the best way to do this?

```
// the number dispatched from this source corresponds to the IDs of items held in storeA
sourceA = new Source<number>('sourceA$');

// create the adapter that handles sourceA
adapterA = ...

// create the store for adapterA and hook up sourceA to a reducer in the adapter
storeA = ...
```

This works fine.

However, then I have another store whose reducers need info from storeA.

```
// adapter B 
adapterB = createAdapter<State>()({
  reducerForSourceA: (state, event) => {
    // here i'd like to be able to access storeA info since I only have the ID in the event, so I need to get info
    // about which object in storeA corresponds to this ID.
    return state;
  }
});

// store B sets up sources that listens for sourceA
store = adapt.init(
  [
    'combat',
    adapterB,
    {}
  ],
  {
    reducerForSourceA: this.someService.sourceA
  }
)```

**Comment by mfp22** [comment]
Cool, thanks for checking it out. I'm currently writing a series explaining how I came up with the syntax for it. https://dev.to/this-is-angular/progressive-reactivity-in-angular-1d40
I actually changed some syntax while writing the article. When initializing a store, initialState and the adapter are passed in in reverse order now. For Angular 14 I also export an `adapt` function that uses `inject` internally so you can call it directly instead of `this.adapt.init`. The changes are in the docs now. I might also be changing the `join` syntax, but I'm pretty sure that's it.

Anyway, the challenge you're talking about exists in most other state management libraries as well. The general solution is either
* you have state in 2 places that should be in one place. Keep A state in A adapter and only the minimal representation in adapter B, then put them together in a selector
* Find a way to provide the extra context in the action payload or source

I have an example of the 2nd approach in this project https://github.com/mfp22/stefanoslig-angular-14-ngrx-nx-realworld-example-app/blob/state-adapt/libs/articles/feature-article-edit/src/lib/article-edit.component.ts

`data$` selects between stores and puts the combined state in the template. When the form is edited, it carries that combined state to the form adapter via the `store.updateData` synthetic source.

If you have more details I can try to help more.

Btw, synthetic sources are a recent concept. Here's my explanation about why I added them to StateAdapt. https://youtu.be/OgjjatkOVE4

**Comment by kyle-mcknight** [comment]
Thanks! I'll give the 2nd option a go as it's easy and what I was already thinking anyway. 

Looking forward to reading up on your docs and watching the videos.

**Comment by kyle-mcknight** [comment]
Do you have an equivalent syntax or helpers for things like NGRX's selectors with props? Or is something like that a no-no with your library?

**Comment by mfp22** [comment]
Oh and I didn't want to barrage my subscribers with my marathon of videos, so the most up-to-date (as of July 5th) NgRx-StateAdapt conversion videos aren't going to be published until August. But the docs are up to date.

**Comment by kyle-mcknight** [comment]
OK, thank you.

> But in that scenario you could even initialize some state with the random number and select from both again.

This is what I was wondering about too, is creating "throwaway" state for some of these types of things considered OK using your library. Thanks!

**Comment by mfp22** [comment]
Well if you have a date, or a random number, or just something that that's nondeterministic, you would have 4 choices:
1. Define it in the selector, making it impure. Not a good option.
2. Define it in a source, like `randomNumber$ = of(Math.random()).pipe(toSource('randomNumber$'));`
3. Initialize it as state in another store like `randomNumberStore = adapt('randomNumber', Math.random());`
4. Initialize it as part of the same store's state. This is the best option.

It would have to be a one-off thing, so #4 would be good. Unless it's part of an event already and #2 would be the best choice. 

But I need more experience with my own library to know for sure... That's why I've been finding random projects on GitHub to convert to StateAdapt. If you know of any projects with weird state patterns, it would be fun to have a look at them.

**Comment by mfp22** [comment]
Weird. I haven't seen that. 

The docs should be current with the latest version, but I haven't kept a change log yet. I will once I release 1.0, which should be happening soon, once it's stable. I have one change left to make, although I think I'll be making a new function and depreciating join. 

The biggest change is switching the order of initialState and the adapter when calling init.

But I don't know why it would correctly infer the observable type but not the type inside. Maybe try restarting the TS server?

**Comment by kyle-mcknight** [comment]
> Weird. I haven't seen that.
> 
> The docs should be current with the latest version, but I haven't kept a change log yet. I will once I release 1.0, which should be happening soon, once it's stable. I have one change left to make, although I think I'll be making a new function and depreciating join.
> 
> The biggest change is switching the order of initialState and the adapter when calling init.
> 
> But I don't know why it would correctly infer the observable type but not the type inside. Maybe try restarting the TS server?

Sorry, I deleted the comment because actually it seems to have resolved itself. Thanks!

**Comment by kyle-mcknight** [comment]
So I ran into this again really and I'm still not really clear on the solution using state-adapt.

I have a store that holds information about some Monster objects.

```
export type MonsterState {
    [id: string]: MonsterInfo;
}
```

I have a store that holds information about tokens. Tokens represent an "instance" of a monster that is participating in combat. The token store just holds an array of tokens which have a `monsterId` property so that we know which monster the token represents.

Lastly, I have a store that holds information about the current state of a combat round.

```
export type CombatState {
    round: number;

    // cards that can be drawn for the monster that is in combat
    [monsterId: string]: AbilityCardInfo[]
}
```

When a round is done, a `roundComplete$` source emits with no value and the combat store listens for this source and increments the round number. In addition it will draw a new card for any monsters currently in the combat store. 

The problem here is that I only want to draw a card for a monster if it also has tokens in the token store.

Your original response was that maybe the states were separated incorrectly and should just be in the same store. If I do that though, then everything is just in one big store, and that seems to go against what you want state-adapt to do so I was trying to keep the stores small.

The other solution you mentioned is to add the context to the source so in this case it would be `roundComplete$`. So I could do something like taking the tokens from the token store and reduce it down to the unique monsters IDs and emit that in the `roundComplete$` source. I don't know if it's just that I'm used to thinking differently, but it just seems weird to add that context to the source. Because if I do that, then that means that anywhere I emit that, which could be from many places would need to access the token store, even though the component really doesn't care about tokens for any other reason. Example is that I have a header component that you click "next" to end the round. But the header wouldn't care about tokens aside from sending them in this source emission. So I feel like I'm then adding a could end up adding lot of dependencies to components really shouldn't care about those dependencies.

Am I understanding your solutions properly here and just need to readjust how I think about things?

**Comment by mfp22** [comment]
Do you have a card store too? What state changes when a card is drawn?

Games are always fun for exploring unique state patterns. Maybe if we can't solve this in another comment or two I'd like to look at the repo.

**Comment by kamcknig** [comment]
Right now I do not have a card store. The cards are stored in the `MonsterInfo` and when a `activateMonster$` source emits, it emits the `MonsterInfo` which the combat store listens for and then adds the cards from the passed `MonsterInfo`.

Which really, that too is a similar situation as what I'm already asking about I suppose. Though in the case of activating the monster, emitting that info in the `activeMonster$` source makes more sense to me than adding the monsters that would need to draw a card to the `roundComplete$` source emission.  It seems more likely that all things listening for the `activateMonster$` would want that `MonsterInfo` where as not all things listening for the `roundComplete$` would need that token/monster ID info just for one reducer.

**Comment by mfp22** [comment]
I'm trying to figure out what this means: "The problem here is that I only want to draw a card for a monster if it also has tokens in the token store."

Depending on what "draw a card" means, you might be able to solve this with selectors.

If it's too hard to explain, feel free to share the repo. Otherwise, we could also do zoom call or something. Eventually I want to have office hours for StateAdapt for anyone to ask questions. It'll take a while to get enough people using though. But this could be like the first office hours.

**Comment by kyle-mcknight** [comment]
> I'm trying to figure out what this means: "The problem here is that I only want to draw a card for a monster if it also has tokens in the token store."

The steps would be to
- activate a monster - this simply says the monster is part of the scenario but doesn't mean there is a physical monster on the board yet
- add one or more tokens to the monster - this means the monster can take part in combat
- at the end of each round (start of the next), draw a card for monsters in combat. right now this draws a card for all active monsters, but I want to change it to draw only for those active monsters that also have tokens

Tokens maybe be "killed" but the monster remains active in the scenario because more tokens could be added later for that monster. I could remove the monster from active when all tokens are gone, and the user could just activate it again later. That would solve the problem, but that's an extra step for the user to take that I don't think they need to. FYI this is a helper app for my Gloomhaven board game group. And leaving the monster "active" (not removing it when it's tokens are all killed) fits with the play style of the game since more tokens could be added later for that monster.

As it pertains to data of for the act of drawing a card, the cards have a `drawn` property. Drawing a card entails looking through the cards in the combat store for a particular monster and finding the last card that has the `drawn` property set to true and then sets the next card in the array to drawn. Or if all cards are drawn, then shuffles the array and sets the first card in the array to drawn.

**Comment by mfp22** [comment]
Okay, I have a much better picture of what's going on now. 

Why does combat state have information that isn't related to the combat? It would be easier if you could assume that if it's part of combat, the monster is in combat. Then you'd draw cards for all monsters in the combat state. If a monster leaves combat, you'd have a source for monsterKilled$ or something, and that would remove it from from combat and add it to a non-combat store. This is similar to how I did the shopping cart example in this repo. 

An alternative could be to have a monsters state that has a property like `inCombat` or something, and a property for cards, and then you only update the cards if it's in combat. 

I hope I understand correctly. I can't really explain a general pattern yet for how I decide to organize state. A relatively flat structure is good I think, and using selectors to combine it into something consumable by components. Maybe that's the best I can do.

Let me know if you think either of those approaches could work.

**Comment by mfp22** [comment]
Oh I'll take a look at the repo too

**Comment by kyle-mcknight** [comment]
> Okay, I have a much better picture of what's going on now.
> 
> Why does combat state have information that isn't related to the combat? It would be easier if you could assume that if it's part of combat, the monster is in combat. Then you'd draw cards for all monsters in the combat state. If a monster leaves combat, you'd have a source for monsterKilled$ or something, and that would remove it from from combat and add it to a non-combat store. This is similar to how I did the shopping cart example in this repo.
> ...

I think I can work with this. Since state-adapt is new, figuring out how to break out state has been a chore for me with how I'm used to thinking in the apps we make at my job right now.

**Comment by mfp22** [comment]
I took a look at the repo real quick, and it looks pretty good. One thing I'll say is the `createSelectors` calls you have are just returning the same object you're passing in, so they aren't necessary, since `createAdapter` is giving you type inference already. 

But I'll look more at it later when I have more time. I'm interested in understanding it better. 

I think the same general rules that the Redux and NgRx teams recommend about state structure probably apply to StateAdapt. StateAdapt is basically a slimmer version of NgRx with all the same principles, but handling effects as part of the source streams instead of through action dispatches.

**Comment by kyle-mcknight** [comment]
So actually I still can't get my head around it despite my last comment hah! I still run into similar issues. Let's take the adding an `inCombat` and a cards property to monster state as an example.

That `inCombat` property could get set to true easily enough when a token is added to the token state (the monster state could also listen for the add token source and set the property on the monster that matches the token's `monsterId` property). But then when a token is removed, I don't know how monster state would know to remove the `inCombat` property because the monster state wouldn't know how many tokens are left for itself (unless I sent that data with the context of the remove token source). Or unless I just add a tokens property to monster state, which would me no need for a separate token state, which of course starts making my monster state fatter and fatter.

**Comment by mfp22** [comment]
Yeah there are lots of details that are relevant. I didn't really know what `tokens` were. I assumed you'd get rid of it if you already had an `inCombat` piece of state, because it would be duplicate state. I thought tokens were just keeping track of which monsters were in combat. It makes sense though that there's more to them.

I have a bunch of family things today, but I'll look more at the repo tonight. 

I haven't looked at the token state yet, but it _sounds_ like it might make more sense as part of combat state. It's describing the combat, right? I don't know. I'm not familiar with the game at all, so I could be wrong. 

I remember struggling with these types of questions a lot when I first learned Redux in 2017, and a bit in 2018. I've designed a lot of state since then and haven't come across any hard problems after the first couple of projects. So hopefully it's a mindset that can be developed, and there aren't problems that are just inherently impossible or impractical to manage in separate reducers/states/stores like NgRx, NGXS and StateAdapt have you do, and I just somehow avoided them all over the past 3-4 years.

Anytime anything gets close to tricky, selectors are usually the things that save the day, since they are so flexible.

**Comment by kyle-mcknight** [comment]
Take all the time you need, appreciate the willingness to help me understand.

> I thought tokens were just keeping track of which monsters were in combat. It makes sense though that there's more to them.

Ahh, nah, tokens here represent individual instances of a monster that is in combat. A monster is basically a template. Holds the stats of the monster, and the tokens represent how many of each of that monster is currently on the board.

> I haven't looked at the token state yet, but it sounds like it might make more sense as part of combat state. It's describing the combat, right? I don't know. I'm not familiar with the game at all, so I could be wrong.

Indeed, I could probably look at it that way and then the info I need would be in the combat state in order to know which to draw for. My first attempts at using state-adapt were simply to make state as small as possible in each store. But tokens in this game are only used to represent monsters in combat so that makes sense to me.

**Comment by kyle-mcknight** [comment]
I have updated the repo to remove the token state and add the tokens to the combat state. This has solved the issue and I think I'm happy with that solution.

**Comment by mfp22** [comment]
I saw this a while ago but forgot to respond. Are things still good?

**Comment by kyle-mcknight** [comment]
Hi, with that change, I actually made the last update I needed on it! So as of now, yes, things are going well, thanks.
