### ISSUE TITLE
unexpected emissions of selector

### ISSUE THREAD

**Issue by xfh** [state-adapt/state-adapt#50]
Hi Mike

I have a selector returning derived state of a state slice `data`. In my real project, I need to get some data based on this selector. I am using the watched store approach, but noticed that it triggers an infinite loop of HTTP requests.

The problem seems to be, that updates to some other state property also triggers updates of my selector. I was expecting the selector memoization to prevent this from happening (same input, same output).

I've forked your state adapt angular stackblitz to provide a minimal reproduction example.

```typescript
export interface MyState {
  data: Entity[];
  otherData?: Record<number, unknown>;
  moreData?: Record<number, unknown>;
}

const stateAdapter = buildAdapter<MyState>()({
  setData: (s, data) => ({ ...s, data }),
  setOtherData: (s, otherData) => ({ ...s, otherData }),
  setMoreData: (s, moreData) => ({ ...s, moreData }),

  selectors: {
    ids: (s) => {
      console.log('selector is called');

      return s.data.map((d) => d.id);
    },
  },
})();
```

[Stackblitz](https://stackblitz.com/edit/state-adapt-angular-avr84a?file=src%2Fapp%2Finfinite-recursion-store.ts) with a clickable example.

Pressing the "Start"-button will start the infinite recursion of state changes. I've limited the execution to 10 iterations.
Pressing the "more-data"-button will set some other state property. If you check the console logs, you will see that it also triggers emission of the selector.

It makes sense to me that any update returns a state change, but it's unexpected, that a selector operating on a state slice is emitting if that state slice hasn't changed (`s.data` remains the same object after 1 start click).

**Comment by mfp22** [comment]
Hey thanks for the StackBlitz repro. It helped me understand the issue quickly.

Here is the cause of this behavior:

Selectors defined in the `selectors` property of the initial adapter are only memoized for the overall state object. If the main state didn't change, they reuse the previous value. But they don't have the ability to memoize specific properties you might access on that state object. Because the selector code doesn't know what those properties are, or even if your state is a primitive, array or object order whatever. So it can't really do anything smart here. I would have to give developers the ability to pass on an actual defaultState when defining the adapter to support this. I don't really plan on doing his right now. And since this selector isn't memoized based on the `data` property, it reruns for any state change, creating a new `ids` array, causing the continual new updates issue. 

To get more fine-grained memoization, you need to first define selectors for the state properties you need, then subsequent selectors can be memoized based on those selectors. This is should fix the issue:

```typescript
const stateAdapter = buildAdapter<MyState>()({
  setData: (s, data) => ({ ...s, data }),
  setOtherData: (s, otherData) => ({ ...s, otherData }),
  setMoreData: (s, moreData) => ({ ...s, moreData }),

  selectors: {
    data: s => s.data,
  },
})({
  ids: (s) => {
    console.log('selector is called');

    return s.data.map((d) => d.id);
  }, 
})();
```

**Comment by xfh** [comment]
Thanks, your suggestion works perfectly fine!

Mental note to myself: always add selectors for state slices if they ar part of downstream dependencies.

Thanks a lot for all your hard work with state adapt and all your informative articles. It's really motivating.

**Comment by mfp22** [comment]
One way to remember might be to define top-level selectors using `state` instead of `s`. So like

```typescript 
const stateAdapter = buildAdapter<MyState>()({
  setData: (state, data) => ({ ...state, data }),
  setOtherData: (state, otherData) => ({ ...state, otherData }),
  setMoreData: (state, moreData) => ({ ...state, moreData }),

  selectors: {
    data: state => state.data,
  },
})({
  ids: (s) => {
    console.log('selector is called');

    return s.data.map((d) => d.id);
  }, 
})(); 
```

The reason I use `s` for downstream selectors is because `selectorStates` is too long. But the `state` and `s` objects are totally different. `s` is a proxy that listens for dependencies being accessed, including `s.state`.

Anyway, I appreciate the kind words. Thanks

**Comment by xfh** [comment]
Thanks for the tip and the explanation.

A helper function to generate selectors for all state properties would be convenient.

ngrx' [createFeature](https://www.ngxs.io/advanced/selector-utils) automatically adds selectors for sate properties.
ngxs supports this with [createPropertySelectors](https://www.ngxs.io/advanced/selector-utils).

Any way, you've already helped me a lot.

**Comment by mfp22** [comment]
Okay, great. I might add that at some point, but for now I used joinAdapters and it's pretty much good enough for me.
