### ISSUE TITLE
observables returned by getRequestSources stop emitting after first emission from error$

### ISSUE THREAD

**Issue by tpsb** [state-adapt/state-adapt#54]
I've tried using `getRequestSources` to interact with a backend API and it looks like the observables returned by the function complete (?) / stop emitting after `error$` emits first value.

I assume the idea with the function was to be able to setup a "long living" pipeline that would keep emitting either from `success$` or `error$`. If that is the case then it'd be great if the code could be fixed to support that.
If the rationale was different, then please explain briefly and close the issue.

Example:
```javascript
let counter = 0;
const subject = new Subject<string>();
const obs = subject.asObservable().pipe(
  map(e => {
    if (typeof e === 'string' && e.startsWith('error')) {
      throw new Error(e);
    } else {
      return e;
    }
  })
);

const { success$, error$ } = getRequestSources('myObs', obs);

const successSub = success$.subscribe(e => console.log('got success:', e));
const errorSub = error$.subscribe(e => console.log('got error:', e));

subject.next('ok ' + (counter++));
subject.next('ok ' + (counter++));
subject.next('error ' + (counter++));
subject.next('ok ' + (counter++));     // not emitted through success$
subject.next('error ' + (counter++));  // not emitted through error$

setTimeout(() => {
  console.log('cleanup');
  successSub.unsubscribe();
  errorSub.unsubscribe();
}, 1000);
```

I've investigated it a little bit and it looks to me that it can be fixed by applying the following change to `catchErrorSource`:

```javascript
export function catchErrorSource<Payload, TypePrefix extends string>(
  typePrefix: TypePrefix,
) {
  return (
    source$: Observable<Payload>,
  ): Observable<Payload | Action<any, `${TypePrefix}.error$`>> =>
    // source$.pipe(catchError(err => of(getAction(`${typePrefix}.error$`, err)))); // original
    source$.pipe(catchError((err, caught) => concat(of(getAction(`${typePrefix}.error$`, err)), caught)));
}
```

I'm not sure what impact this change might have in general but it does seem to fix the problematic behavior described above.
It'd be great if it could be incorporated. If not possible, please suggest a different approach.

**Comment by mfp22** [comment]
It looks like an improvement to me. I didn't know about that second option for catchError. It probably counts as a breaking change officially, but I bet it's closer to what people will want than the current behavior.

If you create a PR I'll merge it within a week and it can be in the next version of StateAdapt. Or I can make the change since it's small.

**Comment by mfp22** [comment]
I'm realizing that this is more complicated than I thought. For cold observables, this produces an infinite loop of errors. @tpsb can you explain more about the hot observable and what is causing the error?

**Comment by mfp22** [comment]
I think I will have to restore the previous behavior for now. If you can change the stream to make the error occur in an inner observable and use `toRequestSource` on the inner observable, that would prevent the error from making it to the main stream, so the subscription would continue. 

For example, instead of 

```typescript
const obs = subject.pipe(
  map(e => {
    if (typeof e === 'string' && e.startsWith('error')) {
      throw new Error(e);
    } else {
      return e;
    }
  })
);
```

You could do 


```typescript
const obs = subject.pipe(
  switchMap(a =>
    of(a).pipe(
      map(e => {
        if (typeof e === 'string' && e.startsWith('error')) {
          throw new Error(e);
        } else {
          return e;
        }
      }),
      toRequestError('prefix'),
    ),
  ),
);
```

Developers most commonly use an HTTP request as their request source, so cold observables are more common. It would be better for beginners to have correct default behavior and more advanced use cases to need this workaround (or use their own HTTP utilities) than for beginners to hit infinite loops and advanced developers to have a smooth experience with a hot source. Also, if these were close tradeoffs, I would err on the side of not causing a breaking change. So, for 2.0 at least, this behavior should stay the same as before. 

I tried to think of ways around this. Maybe options to be passed into these utilities. But these utilities aren't doing much to begin with, and I don't wan't to reimplement RxJS inside a crappy options API, so for anything aside from default behavior, developers should just use RxJS directly rather than these utilities. I am open to ideas if anyone sees a clear solution to this tradeoff though.

**Comment by mfp22** [comment]
When I use the old code and change the test you wrote to this, the test passes. So this workaround is good 
![image](https://github.com/state-adapt/state-adapt/assets/13700926/c1cd2cc5-e135-412e-a1b2-016928da12f2)
