### ISSUE TITLE
Store is not initialized until state observable is subscribed

### ISSUE THREAD

**Issue by rodzappa** [state-adapt/state-adapt#6]
If I don't subscribe the state observable (or don't call it through  an async pipe), the state store isn't initilized.

Steps to reproduce:

1. Comment line 2 on app.component.html from ng-sa-store-services example (pull request sent) and observe Redux devtools to inspect state change when the app load and after, when the toggle button is pressed.

Workaround: Always subscribe the state oberver to initialize the store.

**Comment by mfp22** [comment]
This is intentional, but not 100% settled. Originally state would initialize as soon as `adapt.init` was called. But the issue with that is I would need to provide another method for cleaning up dynamically created states to avoid memory leaks, so I decided to just hook everything together in a single observable chain and let `finalize()` take care of cleaning up the dynamically created state. 

I'm not 100% settled on this. While developing, it is easy to just throw a `.subscribe()` into the constructor. After that, my theory was that the state only matters if something in the UI is going to show something from it, so there would always be some `async` pipe to hold the state there. I am looking for counter-examples of this, but each time I think of one it makes way more sense to show something from the state in an `async` pipe. 

In the shopping cart example, you might add something to the cart and if the cart is not open, then that's a problem, right? Yet, the button to Add to Cart is interested in what is in the cart already, isn't it (so it can show if the item is already in the cart)? And even if it isn't, it seems like every website with a shopping cart shows the total number of items in a badge on the cart icon. 

I don't know every possible app that will be created, so I could imagine a scenario where somebody needs to perform repeated actions that affect some completely hidden app state. I do not love the idea of making people `subscribe()` just to hold the state in place. I'm even more worried about the frustration when people expect state to update but nothing happens. I can try to tell people to think of stores as `scan()` operators and NOT like `BehaviorSubject`s, but it seems like every framework has its landmine for beginners, and this would be it for StateAdapt. 

If I emphasize that `init` is like `scan` every time I talk about it, maybe that will be enough. I did mention in my introduction article that nothing happens until you subscribe: [StateAdapt is reactive, so everything is lazy, like RxJS. So far nothing will actually happen with any state, even if events are pushed into our sources, because nothing is actually subscribing to anything yet.](https://medium.com/weekly-webtips/introducing-stateadapt-reusable-reactive-state-management-9f0388f1850e)

Did you read that article? If you did, then I expect a lot of people to forget this part and maybe I should think seriously about changing the default behavior.

**Comment by rodzappa** [comment]
@mfp22 Ok, my mistake. I've read the article but I haven't paid enought attention to the details. Said that, I just finished reading again and the part of "everythin is lazy" is very subtle for me, due to the facts I had my mind shapped by NgRX behavior.
I have expected whenever I send events, the state store be initialized, but now I understand the state adapter way.
In my particular case, I have events on app.component to deal authentication and guards and other modules or components observe these state changes. So the change events isn't near to observers and the state store is used as a common bus among components. This is one scenario where the actions dispatch could initialize the store, but call the subscribe method is not terrible.
Another parts I wasn't sure if you were talking about internals details or way of use, so I think a demo covering all aspects aborded wil be great, mainly the use of asyncAdapter and custom selectors.
