### ISSUE TITLE
Is it possible to have a selector without memoization?

### ISSUE THREAD

**Issue by andsilmar** [state-adapt/state-adapt#65]
Hi Mike,

I don't know if it is the correct pattern, but sometimes I need a selector without memoization because it is useful to react to each emission when:

1. Using a selector with `@Output`. 
2. When a service sends the same response and a notification will show the message.

For example, when we request a verification code to reset an account password the service will respond with the "A confirmation code has been sent to your email". But then, the user can request another code. Due to the fact that the message is the same, the selector will not emit again (which is the expected default behaviour). This will result in the snackbar not showing. 

For this specific case I think is useful to have access to a version of the selector without memoization. Searching in the web, I found that RxAngular has this feature which is described here: https://www.rx-angular.io/docs/state/setup#output-property-bindings

What do you think of this pattern? Is there a way to solve these cases with StateAdapt?

Thank you in advance for your guidance.

**Comment by mfp22** [comment]
That's an interesting example. I would say no, selectors should always be memoized because they represent states and what you're interested in are either events or just states that are more nuanced than the simple status. If I were you, I would wrap the server response in an object that also includes the date or something. I'm not sure how the user would be able to distinguish the different notifications that are the same anyway. It would probably be nice for the user as well to see unique notifications. But it doesn't have to include the date technically. If you return a new object from any selector or state update, it will emit again because it is technically something new.

**Comment by andsilmar** [comment]
Thanks Mike. It seems that I'm mixing events with state. I will try another approach.
