### ISSUE TITLE
Allow to define a Type for catchErrorSource (@state-adapt/rxjs)

### ISSUE THREAD

**Issue by mathisvester** [state-adapt/state-adapt#72]
In my Angular project i would like to define my error state of a login request as following:

```
export interface AuthState {
  user: Models.User<any> | null;
  error: HttpErrorResponse | null;
}

@Injectable({ providedIn: 'root' })
export class AuthStore {
  readonly login$ = new Source<{ email: string; password: string }>(
    '[Auth] Login'
  );

  private readonly authService = inject(AuthService);

  private readonly accountCreateEmailSession$ = this.login$.pipe(
    concatMap(({ payload }) =>
      this.authService
        .login(payload.email, payload.password)
        .pipe(toRequestSource('[Auth API] Login'))
    )
  );

  private store = adapt(initialState, {
    adapter: authAdapter,
    sources: () => {
      const { success$: loginSuccess$, error$: loginFailed$ } =
        splitRequestSources(
          '[Auth API] Login',
          this.accountCreateEmailSession$
        );

      return {
        loginSuccess: loginSuccess$,
        loginFailed: loginFailed$
      };
    },
  });
}
```

Is there a way to define a Type for this error `loginFailed$`? I think https://angular.io/api/common/http/HttpErrorResponse would be a great fit. Currently I have to type error as `any`.

**Comment by mfp22** [comment]
Sorry for the late reply. 

I don't know what you mean by "Currently I have to type error as any." The error is just typed as `any` in `toRequestSource`. You can have your state be whatever because `any` can be cast to pretty much anything. 

I would have to change it to allow a generic to be passed in for the error type, but then you'd have to explicitly pass in the generics for the action payload and prefix too, because TypeScript doesn't do partial generic inference. I don't think this is worth it, especially because there's little difference between passing in a generic and just casting the resulting type like `loginFailed$ as Observable<Action<HttpErrorResponse, '[Auth API] Login'>>`. TypeScript will just obey you in either case. Not much safety there. And that's basically what TypeScript is already doing when you pass it into `loginFailed: loginFailed$`. So the only added benefit would be if you're doing some intermediate processing with that error. I've never seen anyone do that.

**Comment by mathisvester** [comment]
@mfp22 thanks for your answer.

> I don't know what you mean by "Currently I have to type error as any." The error is just typed as any in toRequestSource. You can have your state be whatever because any can be cast to pretty much anything.

I mean defining the type for error in my state Interface.

Solved it by applying your suggestion and casting the response to `HttpErrorResponse`: https://github.com/mathisvester/ng-x/commit/b2234608e605a524853b8217d31870af42035f21.
