### ISSUE TITLE
Add pending status to getRequestSources / request for recommendation / httpAdapter

### ISSUE THREAD

**Issue by andsilmar** [state-adapt/state-adapt#89]
Hi Mike!

How do you recommend managing the pending status of an http request? Is too common and essential to track that state in order to display information to the user. I think the getRequestSources should provide it and State Adapt should have an httpAdapter, right?

For now this is my solution, which basically adds the `startWith` operator, so it can be easily adopted by State Adapt if you think this solution is going to work. 

<details>

<summary>1. `withHttpStatus` operator</summary>

```typescript
export const withHttpSources = <T, P extends string>(prefix: P): HttpSourcesActions<T, P> =>
  pipe(
    map((data: T) => getAction(`${prefix}.fulfilled$` as const, { status: 'fulfilled' as const, data }) ),
    catchError((error: HttpErrorResponse) =>
      of( getAction(`${prefix}.error$` as const, { status: 'error' as const, error }) ),
    ),
    startWith( getAction(`${prefix}.pending$` as const, { status: 'pending' as const }) ),
  );

```

_Note: Since I'm using the `startWith` operator the source will emit immediately._
</details>

<details>

<summary>2. `getHttpSources` function</summary>

_Note: I'm using getHttpSources instead of getRequestSources to avoid name conflicts with the already existing function in your code_

```typescript
export function getHttpSources<T>(source: Observable<HttpStateSlice<T>>) {
  const shared$ = source.pipe(share());

  const fulfilled$ = shared$.pipe(filter(isHttpFulfilled));
  const error$ = shared$.pipe(filter(isHttpError));
  const pending$ = shared$.pipe(filter(isHttpPending));
  const status$ = shared$.pipe(map((slice) => slice.status));

  return { source$: shared$, fulfilled$, pending$, error$, status$ };
}

```
</details>

<details>
<summary>3. `httpAdapter`</summary>

```typescript
export type HttpStatus = 'fulfilled' | 'error' | 'pending' | 'idle';

const httpAdaper = createAdapter<HttpStatus>()({
  track: <Slice extends { status: HttpStatus }>(_: HttpStatus, { status }: Slice) => status,
  selectors: {
    isPending: (s) => s === 'pending',
    isFulfilled: (s) => s === 'fulfilled',
    isError: (s) => s === 'error',
  },
});

```
</details>

<details>

<summary>Example</summary>

```typescript
interface State {
  createStatus: HttpStatus;
  // other properties
}

const initialState: State = {
  createStatus: 'idle',
};

const adapter = joinAdapters<State>()({
  createStatus: httpAdaper,
})();

const create$ = new Source<Exclude<T, 'id'>>('create$');

const createSources = getHttpSources(
    this.create$.pipe(
      switchMap(({ payload: data }) => this.api.create(data).pipe(withHttpStatus('create')),
      ),
    ),
  );

const state = adapt(initialState, {
    path: 'createUserForm',
    adapter,
    sources: {
      setCreateStatus: createSources.status$,
      // or
      trackCreateStatus: createSources.source$
    },
  });

```
</details>

I'm interested to know your opinion about the idea and if your are planning to add something similar to your code base. 

Regards,

**Comment by mfp22** [comment]
This is a good reminder of another thing on my list of todos that I wish I could have done a long time ago.

However, the benefit is that it's been on my mind so I've had some thoughts over time. I'll share my impressions about what you have there mixed with my own thoughts. 

## 1. Initial state should be `loading`.

Sources should represent events, not states. The only event that occurs in HTTP is when it arrives with data or an error. I just remembered that I already got rid of the `request$` event from `getRequestSources`. Originally it also had a `request$` observable, like 

```typescript
const { request$, success$, error$ } = getRequestSources('interval', interval$);
```

But `request$` would immediately emit and that just felt wrong.

Sending a request isn't a real event, just like subscribing to `timer(1000)` or `whatever$`. You ask for data, and where it comes from is an irrelevant detail. 

So I think `toRequestSource` is still enough. Actually the old version was named `toHttpSource`, and also `getHttpSources`, and I deprecated those in favor of this more minimalistic mindset. 

## 2. There's not 1 single strategy for state that makes sense all the time

In the simplest case, you might have 

```typescript
interface State {
  loading: boolean;
  data: Data;
}

const adapter = joinAdapters<State>()({
  loaded: booleanAdapter,
  data: createAdapter<Data>()({}),
})({
  load: {
    loaded: () => true,
    data: (state, data: Data) => data,
  },
})({
  loading: s => !s.loaded,
  status: s => s.loaded ? 'loaded' : 'loading',
})();

const initialState: State = {
  loaded: false,
  data: initialData,
};

// ... 

store = adapt(initialState, {
  adapter,
  sources: {
    load: inject(DataService).fetch().pipe(toSource('data$')),
  },
});

// this.store.loaded$
// this.store.data$
// this.store.loading$
// this.store.status$
```

Now if we want to support refreshing, there are 2 ways: Clear current state and load, or just load. For clearing current state and loading, that's just `store.reset()`, so we don't need to implement that. For just loading, we can do `store.setLoaded(false)`. But how do we trigger the HTTP request again? Or with a declarative mindset, how do we make the `data$` source in a way that sees with `loaded` is false and is fetching data when that happens?

```typescript
store = adapt(initialState, {
  adapter,
  sources: store => ({
    load: store.loading$.pipe(
      filter(Boolean),
      switchMap(() => inject(DataService).fetch()),
      toSource('data$'),
    ),
  }),
});
```

This is just when an HTTP request is responsible for loading state.

Your example has a POST request. For those, the data is the response still, and it's still something that loads. It's an awkward name... maybe `pending` is better. Or `waiting` would cover both. I thought about creating this adapter and calling it `asyncAdapter`. But it should take in an adapter for `data`, so actually it would be a function like `createAsyncAdapter`. But the source that loads the POST response would probably be something like `created$` or whatever makes sense, and it would chain off of some `submitted$` state from elsewhere or something. 

In the end, there are enough weird scenarios with HTTP that it kind of is difficult to create utilities for them that don't introduce as much complexity as they save. My original HTTP utilities were like that. Even these simplified ones don't fit every scenario well, as you'll see if you look at issues from the past. My advice to people has been to just look at the source code and don't feel bad about doing your own thing. 

It's safest to not create any utilities while so much is still in the air. Deprecating the original HTTP utilities was a big pain. But the struggle I saw people go through to make them fit scenarios they weren't ideal for was worse. I'm not ready to make anything for this and guarantee support. I need to mull it over more, and get more hands-on experience with things, and maybe make incremental improvements. 

Okay.... maybe here's something that could help.

The biggest pain point is how much syntax is

```typescript
const adapter = joinAdapters<State>()({
  pending: booleanAdapter,
  data: createAdapter<Data>()({}),
})({
  load: {
    pending: () => false,
    data: (state, data: Data) => data,
  },
})({
  ready: s => !s.pending,
  status: s => s.pending ? 'pending' : 'ready',
})();
```

That `load` state change particularly feels like boilerplate. The selectors are just nice to have and I don't usually implement them for each project. 

The simplest way to enhance some regular state as some async state would be like:

```typescript
const adapter = createAsyncAdapter(dataAdapter);
```

I just added a utility type called `AdapterState` that I can use to get the `Data` type from `dataAdapter`, or any adapter. So I can do that. And it automatically generates all the stuff we want. 

I guess I could tag it as experimental or something... because I'm sure people will have issues with it.

**Comment by andsilmar** [comment]
Hi Mike... thanks for your feedback and patience waiting for my response. It seems to be that there is no "silver bullet" for this problem because, as you said "There's not 1 single strategy for state that makes sense all the time"...

Here are a couple of notes, just for my records: 

1. I usually not only need a "pending" state, I usually need to trigger "something" when the async operation finishes, for example a toast message. That's why I like so much splitting rxjs sources
2. I think we can borrow the GraphQL terminology: there are query and mutation requests. This can help to define a state pattern with adapters.

I will keep experimenting and thank you again!

**Comment by mfp22** [comment]
1. The UI is derived from state. Alerts, dialogs, etc. should be defined in the template declaratively, not commanded to open. I think I'm going to create a material library inside StateAdapt to wrap Angular Material's imperative APIs. That's been my intention for a while
2. But why?
